### ISSUE TITLE
Support for multi-geomertry types

### ISSUE THREAD

**Issue by thomersch** [pka/t-rex#3]
Cool project, having a lot of fun playing with it.

I encountered an issue while retrieving building data from a table. This table contains Polygons and Multipolygons, which seems to lead into decoding problems, as far as I understand. I tried looking into the code - I am a total Rust noob -, but it looks to me as if it isn't possible to mix types. Is this intended or did I misunderstand something?

Specifically the following log appears:
`thread '<unnamed>' panicked at 'error retrieving column "polygon": Conversion(StringError("cannot convert geometry to Geometry"))', /root/.cargo/registry/src/github.com-88ac128001ac3a9a/postgres-0.11.9/src/rows.rs:204`

**Comment by pka** [comment]
Thanks a lot for your feedback, Tomas.

Currently, all multi-geometries throw errors when reading from PostGIS. This is due to a bug in [rust-postgis](https://github.com/andelf/rust-postgis/issues/6). My plan is to port the rust-postgis WKB reader to  [rust-geo](https://github.com/georust/rust-geo), which solves other restrictions as well.

For the meantime, you can either limit geometries to single types within the where clause (e.g. `GeometryType(geometry)='POLYGON'`), convert them to single geometries partially like `ST_GeometryN(geometry,1)` or fully with [ST_Dump](http://stackoverflow.com/a/31863096/1981751).

**Comment by pka** [comment]
Fixed in v0.5.0
